server:
 - host: localhost
 - user: root
 - passwd: password
 - db: kafka_test

broker:
 - host: localhost
 - port: 9092 

consumer:
 - topic: avrofix
 - consumergroup: test-consumer-group

avro:
 - schema: avrotest.avsc

