server:
 - host: localhost
 - user: root
 - passwd: password
 - db: kafka_test

broker:
 - host: localhost
 - port: 9092 

consumer:
 - topic: kafkatesting
 - consumergroup: kafkatesting

avro:
 - schema: user.avsc

